portal/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :jobs, only: [:create]

end

portal/app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :team

  def running?
    status == 'Running'
  end

  def waiting?
    status == 'Waiting'
  end

  def enqueued?
    running? || waiting?
  end
end

portal/app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :team

  # トップNチームのスコア
  def self.ordered_stats(time:, limit:10)
    scores = where('created_at <= ?', time)
    .group('team_id')
    .order('best_score DESC')
    .limit(limit)
    .pluck('team_id', 'MAX(score) AS best_score')

    # Pre-fetch teams (speed)
    team_hash = Team.pluck(:id, :name).to_h

    score_hash = {}
    scores
    .each do |(team_id, best_score)|
      key = team_hash[team_id]
      score_hash[key] = best_score
    end
    score_hash
  end

  def self.history(time:)
    # Pre-fetch teams (speed)
    team_hash = Team.pluck(:id, :name).to_h

    team_scores = Hash.new {|h,key| h[key] = []}

    where('created_at <= ?', time)
    .order('created_at ASC') # インデックス貼ったほうがいいかも
    .each do |score|
      team_scores[team_hash[score.team_id]] << [score.created_at.in_time_zone, score.score]
    end

    # map for graph
    # [
    #   { name: team1.name, data: [['06:00:00', 123], ['06:05:00', 456]]},
    #   { name: team2.name, data: [['06:00:00', 234], ['06:05:00', 345]]},
    #   ...
    # ]
    team_scores.map { |k, v| { name: k, data: v } }
  end
end

portal/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
  has_many :scores
  has_many :jobs
end

portal/app/models/term.rb
class Term < ActiveRecord::Base
end

portal/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
  belongs_to :team
end

portal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

portal/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    my_team = current_user.team

    if my_team
      @my_scores = Score.where(team: my_team).order(:created_at).reverse_order
    end

    # Fetch stats current - 60min (5 * 12)
    @chart_data = Score.history(time: Time.new)
    @ordered_score = Score.ordered_stats(time: Time.new, limit: 10)

    @jobs = Job.where(status: ['Running', 'waiting']).order(:id)
  end
end

portal/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_user.team.jobs.any?(&:enqueued?)
      flash[:alert] = 'Job already enqueued. Please wait and try later.'
    else
      job = Job.create(team: current_user.team, status: 'Waiting')
      BenchmarkerJob.perform_later(job_id: job.id)
    end
  ensure
    redirect_to :root
  end
end

portal/app/helpers/application_helper.rb
module ApplicationHelper
end

portal/app/helpers/home_helper.rb
module HomeHelper
end

portal/app/helpers/jobs_helper.rb
module JobsHelper
end

portal/app/views/home/index.erb
<h1>Portal</h1>

<h3>ベンチマークの実行状況</h3>

<p>数字はキューの順番です。</p>
<p>現在実行中のベンチマークは青く点滅します。</p>
<p>自分のチームの順番は黄色く表示されます。</p>

<% @jobs.each.with_index do |j,i| %>
  <span class="job-exec-status <%= j.status == 'Running' ? 'job-running' : 'job-waiting' %> <%= current_user.team_id == j.team_id ? 'job-my-team' : 'job-other-team' %>"><%= sprintf("%02d", i+1) %></span>
<% end %>

<div>
  <% if current_user.team.jobs.any?(&:enqueued?) %>
    <%= button_to 'Run Benchmarker', jobs_path, method: :post, class: 'btn btn-primary btn-lg center-block disabled', disabled: true %>
  <% else %>
    <%= button_to 'Run Benchmarker', jobs_path, method: :post, class: 'btn btn-primary btn-lg center-block' %>
  <% end %>
</div>

<h3>各チームのスコア</h3>

<div>
  <%= line_chart @chart_data %>
</div>

<h3>トップスコア</h3>

<div>
  <%= bar_chart @ordered_score %>
</div>

<h3>あなたのチームのスコア</h3>

<% unless @my_scores.empty? %>
  <table class="table">
    <tr>
      <th>時刻</th>
      <th>PASS/FAIL</th>
      <th>スコア</th>
      <th style="width: 500px;">メッセージ</th>
    </tr>
    <% @my_scores.each do |score| %>
      <tr>
        <td><%= score.created_at.in_time_zone('Tokyo').strftime('%H:%M:%S') %></td>
        <td><%= score.pass ? 'PASS' : 'FAIL' %></td>
        <td><%= score.score %></td>
        <td>
          <% if score.message.length > 20 %>
          <span class="clickable expand-message" data-message="<%= score.message %>">
            <%= score.message.slice(0, 20) + '...' %>
          </span>
          <% else %>
          <span><%= score.message %></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

portal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<title>Isucon Portal</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<div class="container">
  <div class="clearfix">
    <div class="pull-left">
      Login: <%= current_user ? (current_user.name + ' (' + current_user.team.name + ')') : 'not login' %>
    </div>
    <div class="pull-right">
      <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-warning' %>
    </div>
  </div>
  <div class="clearfix">
    <% if notice %><p class="notice bg-success"><%= notice %></p><% end %>
    <% if alert %><p class="alert bg-warning"><%= alert %></p><% end %>
  </div>
  <%= yield %>
</div>

portal/app/views/layouts/devise.html.erb
<!DOCTYPE html>

<title>Isucon Portal</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<div class="centered">
  <%= yield %>
</div>